### ISSUE TITLE
Separate brut frontmatter from custom frontmatter

### ISSUE THREAD

**Issue by robinmetral** [robinmetral/brut#45]
Depending on the project, frontmatter objects can get pretty big and there are essentially two kind of keys:

- things used by brut (`template`, `published_date`, `permalink`, `title`, `buildScript`[^1], possibly others like `is_draft`, `excerpt,` or `updated_date` in the future, etc.)
- custom frontmatter (e.g. `featured_image`, `subtitle`)

It would be nice to isolate one from the other. It makes things clearer and avoids scenarios where brut introduces a new key that clashes with an existing custom one.

Custom frontmatter could be under `data` for example:

```yaml
title: My post
published_date: 2024-08-16
data:
  subtitle: Look at what I wrote today
  featured_image: cat.jpg
```

(Inspired by Cobalt again: https://github.com/cobalt-org/cobalt.rs/issues/257)

[^1]: this might get deprecated soon
